version: '3.1'

networks:
  database:
  web:

services:
  mongo:
    image: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: "${USER}"
      MONGO_INITDB_ROOT_PASSWORD:  "${PASSWORD}"
    networks: 
      - database
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8080
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ''
    networks: 
      - database
  app:
    image: my-node
    volumes: 
      - .:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 8080:8080
    networks: 
      - database
      - web
    depends_on: 
      - mongo