version: '3.1'

networks:
  database:
  web:

services:
  mongo:
    image: mongo
    restart: always
    container_name: mooncake
    environment:
      MONGO_INITDB_DATABASE: cake-factory
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD:  root
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks: 
      - database
  app:
    image: my-node
    volumes: 
      - .:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 8081:8081
    networks: 
      - database
      - web
    depends_on: 
      - mongo